
package View;

import view.Login;

/**
 *
 * @author Axelkun02
 */
public class MesasD extends javax.swing.JFrame {

    /**
     * Creates new form MesasDisp
     */
    public MesasD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnProximo_mesasDisp = new javax.swing.JButton();
        btnVoltar_mesasDisp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(116, 2, 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 300, 320));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mesas disponíveis");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 340, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProximo_mesasDisp.setBackground(new java.awt.Color(255, 255, 255));
        btnProximo_mesasDisp.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        btnProximo_mesasDisp.setForeground(new java.awt.Color(255, 255, 255));
        btnProximo_mesasDisp.setText("Próximo");
        btnProximo_mesasDisp.setBorderPainted(false);
        btnProximo_mesasDisp.setContentAreaFilled(false);
        btnProximo_mesasDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProximo_mesasDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo_mesasDispActionPerformed(evt);
            }
        });
        jPanel3.add(btnProximo_mesasDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 320, 80));

        btnVoltar_mesasDisp.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar_mesasDisp.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        btnVoltar_mesasDisp.setForeground(new java.awt.Color(116, 2, 2));
        btnVoltar_mesasDisp.setText("Voltar");
        btnVoltar_mesasDisp.setBorderPainted(false);
        btnVoltar_mesasDisp.setContentAreaFilled(false);
        btnVoltar_mesasDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar_mesasDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar_mesasDispActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar_mesasDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 320, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/VOLTAR.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PROXIMO.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 930, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximo_mesasDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo_mesasDispActionPerformed


     
    }//GEN-LAST:event_btnProximo_mesasDispActionPerformed

    private void btnVoltar_mesasDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar_mesasDispActionPerformed
         Login log = new Login();
         log.show();

         dispose();
    }//GEN-LAST:event_btnVoltar_mesasDispActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesasD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesasD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesasD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesasD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesasD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximo_mesasDisp;
    private javax.swing.JButton btnVoltar_mesasDisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
