
package view;

import javax.swing.JList;
import javax.swing.JOptionPane;


public class SelMesas extends javax.swing.JFrame {

    /**
     * Creates new form selMesas
     */
    public SelMesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnProximo_Sel = new javax.swing.JButton();
        btnVoltar_sel = new javax.swing.JButton();
        lbl_voltar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtObservacoes_Sel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        list_qtd_lugares = new javax.swing.JComboBox<>();
        list_num_mesa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        list_mesas_disp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(116, 2, 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProximo_Sel.setBackground(new java.awt.Color(116, 2, 2));
        btnProximo_Sel.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        btnProximo_Sel.setForeground(new java.awt.Color(255, 255, 255));
        btnProximo_Sel.setText("Próximo");
        btnProximo_Sel.setBorderPainted(false);
        btnProximo_Sel.setContentAreaFilled(false);
        btnProximo_Sel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProximo_Sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo_SelActionPerformed(evt);
            }
        });
        jPanel2.add(btnProximo_Sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 320, 90));

        btnVoltar_sel.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar_sel.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        btnVoltar_sel.setForeground(new java.awt.Color(116, 2, 2));
        btnVoltar_sel.setText("Voltar");
        btnVoltar_sel.setBorderPainted(false);
        btnVoltar_sel.setContentAreaFilled(false);
        btnVoltar_sel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar_selActionPerformed(evt);
            }
        });
        jPanel2.add(btnVoltar_sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 320, 90));

        lbl_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/VOLTAR.png"))); // NOI18N
        jPanel2.add(lbl_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PROXIMO.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 930, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 340));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Escolha sua mesa");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 340, 100));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Observações para a mesa");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        txtObservacoes_Sel.setBackground(new java.awt.Color(255, 255, 255));
        txtObservacoes_Sel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txtObservacoes_Sel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtObservacoes_Sel.setToolTipText("");
        txtObservacoes_Sel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtObservacoes_Sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacoes_SelActionPerformed(evt);
            }
        });
        jPanel1.add(txtObservacoes_Sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 480, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/OBS.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 510, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Número da mesa");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        list_qtd_lugares.setBackground(new java.awt.Color(255, 255, 255));
        list_qtd_lugares.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        list_qtd_lugares.setForeground(new java.awt.Color(153, 153, 153));
        list_qtd_lugares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 lugar\t", "2 lugares", "3 lugares", "4 lugares", "5 lugares", "6 lugares", "7 lugares", "8 lugares", " " }));
        list_qtd_lugares.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        list_qtd_lugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_qtd_lugaresActionPerformed(evt);
            }
        });
        jPanel1.add(list_qtd_lugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, 30));

        list_num_mesa.setBackground(new java.awt.Color(255, 255, 255));
        list_num_mesa.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        list_num_mesa.setForeground(new java.awt.Color(153, 153, 153));
        list_num_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4" }));
        list_num_mesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        list_num_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_num_mesaActionPerformed(evt);
            }
        });
        jPanel1.add(list_num_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 160, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/QTD.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Quantidade de lugares");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/QTD.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Mesas disponíveis");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        list_mesas_disp.setBackground(new java.awt.Color(255, 255, 255));
        list_mesas_disp.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        list_mesas_disp.setForeground(new java.awt.Color(153, 153, 153));
        list_mesas_disp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 disponível", "2 disponíveis", "3 disponíveis", "4 disponíveis", " " }));
        list_mesas_disp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        list_mesas_disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_mesas_dispActionPerformed(evt);
            }
        });
        jPanel1.add(list_mesas_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 230, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/MESAS.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 510, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximo_SelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo_SelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProximo_SelActionPerformed

    private void btnVoltar_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar_selActionPerformed
              Login log = new Login();
                log.show();

                dispose();
               
    }//GEN-LAST:event_btnVoltar_selActionPerformed

    private void txtObservacoes_SelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacoes_SelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacoes_SelActionPerformed

    private void list_mesas_dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_mesas_dispActionPerformed
        String[] mesas = {"Mesa 1", "Mesa 2", "Mesa 3"};
        JList lista = new JList(mesas);
    }//GEN-LAST:event_list_mesas_dispActionPerformed

    private void list_qtd_lugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_qtd_lugaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_qtd_lugaresActionPerformed

    private void list_num_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_num_mesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_num_mesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximo_Sel;
    private javax.swing.JButton btnVoltar_sel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_voltar;
    private javax.swing.JComboBox<String> list_mesas_disp;
    private javax.swing.JComboBox<String> list_num_mesa;
    private javax.swing.JComboBox<String> list_qtd_lugares;
    private javax.swing.JTextField txtObservacoes_Sel;
    // End of variables declaration//GEN-END:variables
}
